import './globals.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
export const metadata = {
  title: 'Muhammad Sufyan jutt',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>

      <body className='bg-black text-white'>
        <div className='relative w-full flex items-center justify-center border-white'> 
        {/* <Navbar /> */}
        </div>
      
        {children}
         {/* <Footer /> */}
      </body>
    </html>
  );
}
